### ISSUE TITLE
Integrate d3-rs-tip with pie chart

### ISSUE THREAD

**Issue by randalpinto** [redsift/d3-rs-pies#3]
Integrate d3-rs-tip with pie chart

**Comment by randalpinto** [comment]
bump.
Would help with dealing with long URLs in pie legend.

**Comment by rahulpowar** [comment]
Merging up the logic between the legend and the chart for the tip is messy in the general case. You may not have legends for every value or you may not wish is to display in the same manner. This is best done by the client with a simple override for the `tipHtml`. I have added an example at https://github.com/redsift/d3-rs-pies/blob/master/examples/brick.html#L35-L43 that shows the one-liner.
