### ISSUE TITLE
Charts not updating legends

### ISSUE THREAD

**Issue by randalpinto** [redsift/d3-rs-pies#4]
Call this twice with different legends. Second time not updated.

_getPieChart(width, height, margin, legend) {
    if (!this._pie) {
      // Create a base one if one doesn't already exist
      this._pie = pies()
        .fill([
          this.fill.uber.color,
          this.fill.hailo.color,
          this.fill.addisonlee.color])
        .displayValue((v) => { return (100 \* v / this._model.data.stats.total).toFixed(0) + '%'; });
    }
    return this._pie.width(width).height(height).outerRadius(height / 3).legend(legend).margin(margin);
  }

  _getPattern(color) {
    console.log('sift-taxi: _getPattern: ', color);
    let p = diagonals('highlight-fill-' + color, patterns.diagonal1);
    p.foreground(presentation10.lighter[color]);
    p.background(presentation10.darker[color]);
    console.log('sift-taxi: _getPattern: ', p.url());
    return p;
  }

**Comment by randalpinto** [comment]
bump. 
This is the one I mentioned in the last scrum.

**Comment by rahulpowar** [comment]
Working
